### ISSUE TITLE
What is the license? am i allowed to repack for arch linux package and publish in AUR ?

### ISSUE THREAD

**Issue by ajiepangestu** [hainguyents13/mechvibes#121]
there is no version for arch linux, am i allowed to repack this awesome app for arch linux package and publish in AUR ? (https://aur.archlinux.org). Still write mechvibes.com for credit

**Comment by hainguyents13** [comment]
yes you are welcome to do that

**Comment by ajiepangestu** [comment]
done, thanks https://aur.archlinux.org/packages/mechvibes/

**Comment by Beryesa** [comment]
> yes you are welcome to do that

Hi, what are the licence for audio files, are they CC0 CC-BY CC-BY-SA etc or…? Thank you!

For context:
I would like to make a much lightweight (low level) and better-integrated app for modern Linux systems, which this app won't be able to support as is, due to security restrictions on the new stack. 
Can you please clarify this, thank you!

**Comment by throwaway69420-69420** [comment]
@Beryesa any updates on the licence issue?

**Comment by NotLazy** [comment]
#67
