### ISSUE TITLE
KEY DOWN / KEY UP sounds

### ISSUE THREAD

**Issue by mrender** [hainguyents13/mechvibes#21]
One thing that sounds strange is that we hear the whole key trajectory sound, going down and getting back up, although we did not release the key.

It would be interesting to have 2 sounds: one for down, one other for up.

**Comment by hainguyents13** [comment]
I thought of that in the very beginning, but there will be a lot of problems with it. but I will try when I have time

**Comment by mefleacuzimtiny** [comment]
A suggestion for the sound effects to be more efficient so there's a seamless connection between the sounds:
Maybe there can be three versions of each sounds:
On click, On release, and Full
On full would play if the button has been held for < 0.5 ms or some other arbitrary small amount of time. If it exceeds this, then only the on click sound effect could be played, and then, when the release event occurs, then the on release sound effect could be played.

**Comment by Riumilk** [comment]
This feature not only would be nice, but I'd say it is kind of necessary..
There are multiple ways to make this work, like: 

Having multiple audio files assigned to a specific state of keypress  
ie: `"1": "down.wav", "up.wav"`
And add a toggle for the function, so that if you don't want to use it, it plays down and up sequentially like if it was a single file.

To a more involved one, like still mantaining a single audio file but with the user stating in the config when the down state ends.
ie: `"1": "down.wav" "x", `
'X' would be in ms, and you would need to specify only when the down state ends. 
Just use the start of the audio file for the start of key down until 'x' and use 'x' as the start of the up state

Another option is to get that value without changing configs at all
Just take the whole length of the audio file and use the first half for key down and second half for key up. 

Thing is, properly documenting it in a 'how to' for creating a sound pack would also be necessary.

Also, and I can't stress this enough, I do not know how this could be accomplished by code, I mean, I don't know anything, this is just me saying stuff

**Comment by NotLazy** [comment]
@rivmi Thanks for your feedback. I've already made plans about how to structure the next (couple) versions of configs, including abstracting sounds into a number of configurable files and clips, with both being supported within one pack.

Here's a shorter version of what I have so far, that covers your concerns:
```javascript
{
	"sounds": {
		// play a clip of the file
		"keydown": {
			"file": "#/sound.ogg", // #/ marks the root of the soundpack
			"clip": [2186, 281], // ["start", "length"]
		},
		"keyup": {
			"file": "#/sound.ogg",
			"clip": [3251, 281],
		},

		// play the whole file
		"key_down": {
			"file": "#/sound2.ogg",
		},
		"key_up": {
			"file": "#/sound2_up.ogg",
		},
	}

	// key definitions
	"defines": {
		// format
		"keyCode": ["keyDown", "keyUp"]
		// definitions

		// define one sound for key down only
		"1": ["keydown"],

		// define two sounds for key down and key up
		"2": ["key_down", "keyup"],
	}
}
```
