### ISSUE TITLE
Delay on initial key stroke (solved (sorta))

### ISSUE THREAD

**Issue by Thefaroah** [hainguyents13/mechvibes#222]
After starting Mechvibes, I would minimize (or close) the window that appears.
If I let the window remain on screen, the delay does not occur.
I shrink the window so it's not so obvious.

**Comment by AspectOfJerry** [comment]
#12 
#13 
#142 
#151

**Comment by haadisaqib** [comment]
This issue still exists as of 06/06/24. If a user is idle and starts typing, there is a slight delay in the first few keystrokes. This minor inconvenience only happens if the application is in the system tray. 

I don't know the issue exactly but it could be the app going to sleep. In that case, we could use 'powerSaveBlocker
' from electron. I'll be back to report my findings :)
