### ISSUE TITLE
when mechvibes dont show the sound bar and no sound

### ISSUE THREAD

**Issue by UniquerRedEye** [hainguyents13/mechvibes#224]
please fix this glitch hainguyents

**Comment by AspectOfJerry** [comment]
Can you provide a screenshot?
Thanks

**Comment by DANIELSADS** [comment]
![image](https://user-images.githubusercontent.com/125215536/218331613-c2ebbc6a-cfcd-45a5-9ae1-523fe4e3deb1.png)

It's like this for hours. I've been tying to uninstall and install but it doesn't do anything, do you have a solution for this?

**Comment by AspectOfJerry** [comment]
It looks like you are opening a `.HTML` file in `/src`. Did you download the source code by any chance instead of the `.exe`?

You can go to the [releases page](https://github.com/hainguyents13/mechvibes/releases/tag/v2.3.0) and download [Mechvibes.Setup.2.3.0.exe](https://github.com/hainguyents13/mechvibes/releases/download/v2.3.0/Mechvibes.Setup.2.3.0.exe).

Make sure to run the executable (`.exe`) and not the source code files!
