### ISSUE TITLE
Loading same file multiple times on website demo

### ISSUE THREAD

**Issue by PushpenderSaini0** [hainguyents13/mechvibes#297]
It looks like some config's have `key_define_type = "multi"` but have same file listed for multiple keys.

Check [this](https://mechvibes.com/sound-packs/custom-sound-pack-1203000000075/dist/config.json)

This will load the same file multiple times wasting resources.
Is the demo page open source ? I would love to help fixing this issue !

![image](https://github.com/hainguyents13/mechvibes/assets/54404738/1cf46186-dee3-4ac0-8f0b-b3c497a3e841)

**Comment by PushpenderSaini0** [comment]
It looks like the docs folder was removed in this commit 80f13a14ca25bd499a37760f480a26e182bca2c6

**Comment by NotLazy** [comment]
I'm not sure what the docs folder has to do with this, but this is because it is almost the exact same code as what runs in the app. The app operates this way to ensure that when the same sound is expected to play twice at once, the first one doesn't get cut off or not played at all. A solution to this would of course be an audio pool, but that adds complexity, and does still have the possibility of overflowing if you press keys too fast or if the sounds in the pack are longer.

**Comment by PushpenderSaini0** [comment]
Ok , i finally found the issue.

Let me explain, under the meme tag, i was trying to play `Vine Boom` and it was stuck on loading (Firefox Mac OS X ).
When i checked network tab a lot of files were loaded i thought this could be an issue and raised it here.

As you have explained the cached version is being used i can see this could not have caused the issue,
after some debugging i saw the audio played on `chrome` but not on `firefox`.

I went through the code and saw for this particular sound `checkIfAllSoundLoaded()` callback was not being called.

But Why ? all the code looked fine to me.
After some more debugging i finally found the issue !

This codec used in the file is not supported in Firefox !
also it looks like the `.mp3` file is actually a `.mov`

- Output
> Vine.mp3: ISO Media, Apple QuickTime movie, Apple QuickTime (.MOV/QT)

![image](https://github.com/hainguyents13/mechvibes/assets/54404738/4c4d3651-3ca3-43f3-8339-d3a45cfe8ead)

So this is what's happening in the end.
![image](https://github.com/hainguyents13/mechvibes/assets/54404738/b19a490f-06fe-4900-b84a-32fc1c51b5e4)

The resolve is never being called on the promise hence it will never be able to run anyting after await ! 
Which is the code responsible to removing the `loading` class and the `loading` state being set to false.

```javascript
$(this).text("Loading...");
current_pack = await loadPack(pack); // code won't reach below this if promise won't resolve
// lock in new pack
$(parent).removeClass("loading").addClass("testing").addClass("cached");
loading = false;
```

Now it's okay if one sound loading fails but this also make loading state stuck hence no other pack can be tried 😞 .

### Solution 

I would suggest to use the `loaderror` event to show error to user and reset the state if we have such issue.

![image](https://github.com/hainguyents13/mechvibes/assets/54404738/c82fa7cd-1587-417b-a0b1-f397ebd8be78)

**Comment by NotLazy** [comment]
@PushpenderSaini0 This is still a website issue right? Not an app issue?

I do see that improper container encoding is definitely an issue I'll need to look into solving, as a .mov disguised as a .mp3 is a very bad thing, so I'll look into detecting this on the server side.

But I'll have to review the website code to see if this is fixable or not, as in howler.js, the library we use in the app, it's not fixable, as howler doesn't seem to properly inform us when an error occurs. I think this is due to the webaudio api though, not howler.

**Comment by PushpenderSaini0** [comment]
> This is still a website issue right? Not an app issue?

Yes this is just a website issue !

> Howler doesn't seem to properly inform us when an error occurs.

Can you try the `loaderror` event ?
I was able to get a call on this even when loading this `mp3`

**Comment by NotLazy** [comment]
> > Howler doesn't seem to properly inform us when an error occurs.
> 
> Can you try the `loaderror` event ? I was able to get a call on this even when loading this `mp3`

I likely can, since it's a website issue. I was saying that I can't do this in the app, because howler only calls loaderror on certain loaderrors, not all loaderrors.

**Comment by NotLazy** [comment]
@PushpenderSaini0 Please try now. I've added errors to all three load requests which fall back onto a try/catch near the `await loadPack()` call

**Comment by PushpenderSaini0** [comment]
Thank you, @NotLazy for fixing this. 🚀  
- It's working as expected !
- Shows loading error, and does not block other packs !
![image](https://github.com/hainguyents13/mechvibes/assets/54404738/bd898d8d-ff2a-4d3e-be48-329fcee5472c)
