### ISSUE TITLE
Sound stops after a while on Macbook Pro MacOS 14.5

### ISSUE THREAD

**Issue by MathiasF1do** [hainguyents13/mechvibes#318]
Sound stops after a while on Macbook Pro MacOS 14.5, the app is still working but seems a bit buggy and the sound is not working. Also no errors in the logs.

**Comment by NotLazy** [comment]
#13

**Comment by MathiasF1do** [comment]
Not the same issue. And this issue is still on going.

**Comment by MathiasF1do** [comment]
And the app just becomes blank when this happens.

No sound and the app is blank and needs to reboot it and it works again until I logout of the mac then it bugs again.

**Comment by NotLazy** [comment]
It's related to #13 because the issue is related to electron putting the renderer process to sleep after some time of inactivity. But the issue surfaces when the renderer process's memory gets corrupted while it's asleep, so it can't wake back up. Restarting the app via the tray icon fixes the issue.

Because this is an issue with electron, and electron doesn't appear to fire an event when this issue occurs, it makes it really difficult to have the app fix itself when this occurs.
