### ISSUE TITLE
Please publish 2.3.5 with all fixes

### ISSUE THREAD

**Issue by marmotz** [hainguyents13/mechvibes#332]
Issues was marked as resolved (see https://github.com/hainguyents13/mechvibes/issues/169) but no new release with these fixes.

Please publish a new release.

**Comment by NotLazy** [comment]
The reason 2.3.5 hasn't yet been released is because it has target goals that have not yet been met, mostly due to life getting in the way for all the active contributors to this project.

That being said, although the current state of the code on the master branch is not entirely functional, you're more than welcome to clone the repo and build it yourself if you so wish.

Otherwise, we'll continue working towards the goals of 2.3.5 when we have time.
