### ISSUE TITLE
I cant select the keyboard type on mech vibes(macos)

### ISSUE THREAD

**Issue by SirOctoCat** [hainguyents13/mechvibes#81]
![Screen Shot 2021-04-19 at 6 25 39 PM](https://user-images.githubusercontent.com/77217304/115310901-a5ff1700-a13c-11eb-80b8-45715b9631cf.png)

**Comment by Lil987** [comment]
I had that same problem.  Uninstall the program and delete all files from it.  When reinstalling, instead of clicking the latest version under downloads, click all releases.  In my case there was a pre-release.  When I downloaded the pre-release, the program worked again.  Just make sure you select the most recent version and you should be good.

**Comment by NotLazy** [comment]
#250
