### ISSUE TITLE
Default sounds not showing up when I open the app

### ISSUE THREAD

**Issue by Gloxyyy** [hainguyents13/mechvibes#85]
It was completely fine for a while and today the sounds arent showing up anymore when I open the app.

**Comment by sxripted** [comment]
same

**Comment by oMiniLuo** [comment]
I have the exact same problem.

**Comment by Lil987** [comment]
I had that same problem.  Uninstalled the program and delete all files from it.  When reinstalling, instead of clicking the latest version under downloads, click all releases.  In my case there was a pre-release.  When I downloaded the pre-release, the program worked again.  Just make sure you select the most recent version and you should be good.

**Comment by NotLazy** [comment]
potentially #250 ?
